### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by coollofty** [GiusTex/ComfyUI-DiffusersImageOutpaint#5]
![Screeb-20241005103935](https://github.com/user-attachments/assets/99bed91c-64d6-48cd-b17e-06d750d06d0d)

May I ask: How to provide the input in the red circle? Also, is the use of ksampler correct?

**Comment by GiusTex** [comment]
There is another node in the extension, the diffusers outpaint text encode, you can find all the nodes under "diffusers"

**Comment by GiusTex** [comment]
About the vae encode for inpainting, you can pass the pad image node's mask

**Comment by coollofty** [comment]
Could you provide a standard workflow json as an example to put in this repo? I still haven't solved it ~_~

**Comment by GiusTex** [comment]
> Could you provide a standard workflow json as an example to put in this repo? I still haven't solved it ~_~

[Done](https://github.com/GiusTex/ComfyUI-DiffusersImageOutpaint/blob/main/Diffusers-Outpaint-Workflow.json)

I suggest you to update the extension, also, I fixed a bug that occurred when updating the prompt

**Comment by coollofty** [comment]
Thank you for fast reply, but I have been testing several images in a row and when I run the second one, this error will be reported


> 2024-10-05 21:20:28,722- root:393- ERROR- Traceback (most recent call last):
>   File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffusersImageOutpaint\nodes.py", line 98, in expand_image
>     margin_x = (width - new_width) // 2
>                         ^^^^^^^^^
> UnboundLocalError: cannot access local variable 'new_width' where it is not associated with a value
>

![1234](https://github.com/user-attachments/assets/ceac0324-48f0-446f-8445-525127644f20)


source image is 512x512

**Comment by GiusTex** [comment]
Try updating and restaring now, then tell me, I added some lines

**Comment by coollofty** [comment]
I have updated and the current repo version is 43bf24A, workflow is the same, but the problem still:

```
2024-10-06 09:54:30,203- root:822- ERROR- Failed to validate prompt for output 351:
2024-10-06 09:54:30,203- root:842- ERROR- * LoadDiffusersOutpaintModels 637:
2024-10-06 09:54:30,203- root:844- ERROR-   - Value not in list: vae: 'sdxl-vae-fp16-fix' not in ['controlnet-union-sdxl-1.0', 'RealVisXL_V5.0_Lightning', 'sdxl_vae-fp16']
2024-10-06 09:54:30,203- root:846- ERROR- Output will be ignored
2024-10-06 09:54:30,203- root:627- WARNING- invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-10-06 09:54:36,750- root:595- INFO- got prompt
2024-10-06 09:54:37,107- root:392- ERROR- !!! Exception during processing !!! cannot access local variable 'new_width' where it is not associated with a value
2024-10-06 09:54:37,128- root:393- ERROR- Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-DiffusersImageOutpaint\nodes.py", line 104, in expand_image
    margin_x = (width - new_width) // 2
                        ^^^^^^^^^
UnboundLocalError: cannot access local variable 'new_width' where it is not associated with a value

2024-10-06 09:54:37,129- root:138- INFO- Prompt executed in 0.36 seconds
```

**Comment by GiusTex** [comment]
> Result is interesting

What are you using?

**Comment by GiusTex** [comment]
It has nothing to do with this problem though

**Comment by coollofty** [comment]
The code has been updated, I have checked and it has indeed been updated, but the problem still. So, can this issue be resolved?

**Comment by GiusTex** [comment]
Try it, it should work

**Comment by coollofty** [comment]
Well, it should be resolved. thanks ^_^
